os: linux
arch : PPC64LE
git:
  clone: false

before_install: 
  - git clone http://github.com/${TRAVIS_REPO_SLUG} ${HOME}/TravisDemo
  - pwd
  - cd ${HOME}/TravisDemo
  - pwd
  - ls -l

script:
  - env

install:
  - env
  - ls -l

