os: linux
arch : PPC64LE
git:
  clone: false

before_install: 
  - echo "In Before Install"
  - echo "-----------------------"
  - git clone http://github.com/${TRAVIS_REPO_SLUG} ${HOME}/TravisDemo
  - pwd
  - cd ${HOME}/TravisDemo
  - pwd
  -ls -l

script:
  - echo "In Script"
  - echo "-----------------------"
  - env

install:
  - echo "In Install"
  - echo "-----------------------"
  - env
  - ls -l

